spring.application.name=production_planner

planner.api.create.test.data=true

spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
# In-memory H2 database configuration
spring.datasource.url=jdbc:h2:file:./h2/production_planner;AUTO_SERVER=TRUE
#spring.datasource.url=jdbc:h2:mem:production_planner_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 console for easier debugging
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
